package net.colindodd.weight.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import net.colindodd.weight.model.Reading;
import net.colindodd.weight.model.Weight;

import net.colindodd.weight.model.ReadingDao;
import net.colindodd.weight.model.WeightDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig readingDaoConfig;
    private final DaoConfig weightDaoConfig;

    private final ReadingDao readingDao;
    private final WeightDao weightDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        readingDaoConfig = daoConfigMap.get(ReadingDao.class).clone();
        readingDaoConfig.initIdentityScope(type);

        weightDaoConfig = daoConfigMap.get(WeightDao.class).clone();
        weightDaoConfig.initIdentityScope(type);

        readingDao = new ReadingDao(readingDaoConfig, this);
        weightDao = new WeightDao(weightDaoConfig, this);

        registerDao(Reading.class, readingDao);
        registerDao(Weight.class, weightDao);
    }
    
    public void clear() {
        readingDaoConfig.clearIdentityScope();
        weightDaoConfig.clearIdentityScope();
    }

    public ReadingDao getReadingDao() {
        return readingDao;
    }

    public WeightDao getWeightDao() {
        return weightDao;
    }

}
