package net.colindodd.weight.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "READING".
*/
public class ReadingDao extends AbstractDao<Reading, Long> {

    public static final String TABLENAME = "READING";

    /**
     * Properties of entity Reading.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Timestamp = new Property(0, long.class, "timestamp", true, "_id");
        public final static Property WeightId = new Property(1, Long.class, "weightId", false, "WEIGHT_ID");
    }

    private DaoSession daoSession;


    public ReadingDao(DaoConfig config) {
        super(config);
    }
    
    public ReadingDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"READING\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: timestamp
                "\"WEIGHT_ID\" INTEGER NOT NULL );"); // 1: weightId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"READING\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Reading entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getTimestamp());
        stmt.bindLong(2, entity.getWeightId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Reading entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getTimestamp());
        stmt.bindLong(2, entity.getWeightId());
    }

    @Override
    protected final void attachEntity(Reading entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Reading readEntity(Cursor cursor, int offset) {
        Reading entity = new Reading( //
            cursor.getLong(offset + 0), // timestamp
            cursor.getLong(offset + 1) // weightId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Reading entity, int offset) {
        entity.setTimestamp(cursor.getLong(offset + 0));
        entity.setWeightId(cursor.getLong(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Reading entity, long rowId) {
        entity.setTimestamp(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Reading entity) {
        if(entity != null) {
            return entity.getTimestamp();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Reading entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getWeightDao().getAllColumns());
            builder.append(" FROM READING T");
            builder.append(" LEFT JOIN WEIGHT T0 ON T.\"WEIGHT_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Reading loadCurrentDeep(Cursor cursor, boolean lock) {
        Reading entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Weight weight = loadCurrentOther(daoSession.getWeightDao(), cursor, offset);
         if(weight != null) {
            entity.setWeight(weight);
        }

        return entity;    
    }

    public Reading loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Reading> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Reading> list = new ArrayList<Reading>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Reading> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Reading> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
